name: MySchedule
options:
  bundleIdPrefix: jp.yoshitak
  developmentLanguage: ja
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: ja
  xcodeVersion: "15.3"
settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: KT9XC28AF5
packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint
    version: 0.54.0
targets:
  MySchedule:
    type: application
    platform: iOS
    sources:
      - MySchedule
    settings:
      base:
        INFOPLIST_FILE: MySchedule/Info.plist
        DEVELOPMENT_LANGUAGE: jp
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
      configs:
        debug:
          OTHER_SWIFT_FLAGS: $(inherited) -Xfrontend -warn-long-expression-type-checking=500 -Xfrontend -warn-long-function-bodies=500
    postCompileScripts:
      # SwiftLintで静的解析と自動修正
      - path: ./Scripts/XcodeGen/swiftlint.sh
        name: Run SwiftLint
    buildToolPlugins:
      - plugin: SwiftLintPlugin
        package: SwiftLint
  MyScheduleTests:
    type: bundle.unit-test
    platform: iOS    
    sources:
      - MyScheduleTests
    dependencies:
      - target: MySchedule
  MyScheduleUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - MyScheduleUITests
    dependencies:
      - target: MySchedule
schemes:
  MySchedule:
    build:
      targets:
        MySchedule: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - MySchedule
      targets:
        - name: MyScheduleTests
          parallelizable: true
          randomExecutionOrder: true
        - name: MyScheduleUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
