version: 2.1

orbs:
  slack: circleci/slack@4.8

commands:
  notify_slack_fail:
    steps:
    - slack/notify:
        channel: C06UEBP86S0
        event: fail
        template: basic_fail_1

jobs:
  build:
    macos:
      xcode: 15.1.0
    steps:
      - checkout
      - run: sh skipPackagePluginValidation.sh
      - run: sh skipMacroValidation.sh 
      - run: bundle install
      - run: bundle exec fastlane generate_project
      - run: bundle exec fastlane test
      - notify_slack_fail

workflows:
  code_health:
    jobs:
      - build:
          context: myschedule-ios
