version: 2.1

orbs:
  slack: circleci/slack@4.8

executors:
  gen2_medium:
    macos:
      xcode: 14.3.1
    resource_class: macos.x86.medium.gen2
commands:
  notify_slack_fail:
    steps:
    - slack/notify:
        channel: C06UEBP86S0
        event: fail
        template: basic_fail_1

jobs:
  build:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run: sh skipPackagePluginValidation.sh
      - run: sh skipMacroValidation.sh 
      - run: bundle install
      - run: bundle exec fastlane generate_project
      - run: bundle exec fastlane test
      - notify_slack_fail

workflows:
  code_health:
    jobs:
      - build:
          executor: gen2_medium
          context: myschedule-ios
