version: 2.1

orbs:
  slack: circleci/slack@4.8

commands:
  notify_slack_fail:
    steps:
    - slack/notify:
        channel: D06UQJ5D6DP
        event: fail
        template: basic_fail_1

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world"
      - notify_slack_fail
