# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "テストを実行する"
  lane :test do
    scan()
  end

  desc "XcodeGenでプロジェクトファイルを生成する"
  lane :generate_project do
    xcodegen(spec: "project.yml")
  end

  desc 'Analyze'
  desc 'This may comment to pull request'
  lane :analyze do
    create_lint_config

    sh <<-EOS
cd ../;
swiftlint lint --reporter json | linterbot soseki557/MySchedule-iOS $CI_PULL_REQUEST
    EOS

    delete_lint_config
  end

  def create_lint_config
    File.delete('../.swiftlint-ci.yml') if File.exist?('../.swiftlint-ci.yml')
    require 'yaml'
    config = YAML.load_file('../.swiftlint.yml')
    config['reporter'] = 'json'
    open('../.swiftlint-ci.yml', 'w') do |file|
      YAML.dump(config, file)
    end
  end

  def delete_lint_config
    File.delete('../.swiftlint-ci.yml')
  end
end
