name: Danger
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.9 # Xcode15系
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
